#!/usr/bin/env python3
"""
Unified Token Setup Script

Sets up API tokens for HuggingFace and Modal services.
Combines functionality from setup_hf_token.py and setup_modal_token.py.

Usage:
    python scripts/setup_tokens.py --hf          # Setup HuggingFace token
    python scripts/setup_tokens.py --modal       # Setup Modal token
    python scripts/setup_tokens.py --all         # Setup all tokens
    python scripts/setup_tokens.py --check       # Check token status
"""

import argparse
import os
import sys
from pathlib import Path
from getpass import getpass


def get_project_root() -> Path:
    """Get project root directory."""
    return Path(__file__).resolve().parent.parent


def load_env_file(env_path: Path) -> dict:
    """Load existing .env file into dict."""
    env_vars = {}
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip().strip('"').strip("'")
    return env_vars


def save_env_file(env_path: Path, env_vars: dict):
    """Save dict to .env file."""
    with open(env_path, 'w') as f:
        f.write("# LLM Training Pipeline Environment Variables\n")
        f.write("# Auto-generated by setup_tokens.py\n\n")
        for key, value in sorted(env_vars.items()):
            f.write(f'{key}="{value}"\n')


def setup_hf_token(env_path: Path, token: str = None) -> bool:
    """Setup HuggingFace token."""
    print("\n=== HuggingFace Token Setup ===")
    print("Get your token from: https://huggingface.co/settings/tokens")
    print("Required permissions: Read access to repos\n")

    if token is None:
        token = getpass("Enter HuggingFace token (hidden): ").strip()

    if not token:
        print("Error: No token provided")
        return False

    # Validate token format
    if not token.startswith('hf_'):
        print("Warning: Token doesn't start with 'hf_'. Are you sure this is correct?")
        confirm = input("Continue anyway? (y/n): ").strip().lower()
        if confirm != 'y':
            return False

    # Load existing env and update
    env_vars = load_env_file(env_path)
    env_vars['HF_TOKEN'] = token
    env_vars['HUGGING_FACE_HUB_TOKEN'] = token

    save_env_file(env_path, env_vars)

    print(f"HuggingFace token saved to {env_path}")
    return True


def setup_modal_token(env_path: Path, token_id: str = None, token_secret: str = None) -> bool:
    """Setup Modal token."""
    print("\n=== Modal Token Setup ===")
    print("Get your tokens from: https://modal.com/settings")
    print("Or run: modal token new\n")

    if token_id is None:
        token_id = getpass("Enter Modal Token ID (hidden): ").strip()
    if token_secret is None:
        token_secret = getpass("Enter Modal Token Secret (hidden): ").strip()

    if not token_id or not token_secret:
        print("Error: Both Token ID and Token Secret are required")
        return False

    # Load existing env and update
    env_vars = load_env_file(env_path)
    env_vars['MODAL_TOKEN_ID'] = token_id
    env_vars['MODAL_TOKEN_SECRET'] = token_secret

    save_env_file(env_path, env_vars)

    print(f"Modal tokens saved to {env_path}")
    return True


def check_tokens(env_path: Path):
    """Check status of all tokens."""
    print("\n=== Token Status ===\n")

    env_vars = load_env_file(env_path)

    # HuggingFace
    hf_token = env_vars.get('HF_TOKEN') or env_vars.get('HUGGING_FACE_HUB_TOKEN')
    if hf_token:
        masked = hf_token[:8] + '...' + hf_token[-4:] if len(hf_token) > 12 else '****'
        print(f"HuggingFace: CONFIGURED ({masked})")
    else:
        print("HuggingFace: NOT CONFIGURED")

    # Modal
    modal_id = env_vars.get('MODAL_TOKEN_ID')
    modal_secret = env_vars.get('MODAL_TOKEN_SECRET')
    if modal_id and modal_secret:
        masked_id = modal_id[:8] + '...' if len(modal_id) > 8 else '****'
        print(f"Modal: CONFIGURED (ID: {masked_id})")
    else:
        print("Modal: NOT CONFIGURED")

    print(f"\n.env location: {env_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Setup API tokens for LLM Training Pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/setup_tokens.py --hf          # Setup HuggingFace only
    python scripts/setup_tokens.py --modal       # Setup Modal only
    python scripts/setup_tokens.py --all         # Setup all tokens
    python scripts/setup_tokens.py --check       # Check current status
        """
    )

    parser.add_argument('--hf', action='store_true', help='Setup HuggingFace token')
    parser.add_argument('--modal', action='store_true', help='Setup Modal tokens')
    parser.add_argument('--all', action='store_true', help='Setup all tokens')
    parser.add_argument('--check', action='store_true', help='Check token status')
    parser.add_argument('--env-file', type=str, help='Path to .env file')

    args = parser.parse_args()

    # Determine .env path
    root = get_project_root()
    if args.env_file:
        env_path = Path(args.env_file)
    else:
        env_path = root / '.env'

    # If no arguments, show help
    if not any([args.hf, args.modal, args.all, args.check]):
        parser.print_help()
        sys.exit(0)

    # Check status
    if args.check:
        check_tokens(env_path)
        sys.exit(0)

    # Setup tokens
    success = True

    if args.hf or args.all:
        if not setup_hf_token(env_path):
            success = False

    if args.modal or args.all:
        if not setup_modal_token(env_path):
            success = False

    # Final status
    print("\n" + "=" * 40)
    check_tokens(env_path)

    if success:
        print("\nSetup completed successfully!")
    else:
        print("\nSome tokens could not be configured.")
        sys.exit(1)


if __name__ == '__main__':
    main()
